//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.OtelKursach2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Доступ.
    /// </summary>
    // *** Start programmer edit section *** (Доступ CustomAttributes)

    // *** End programmer edit section *** (Доступ CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДоступE", new string[] {
            "КодДоступа as \'Код доступа\'",
            "Доступ as \'Доступ\'",
            "Комната as \'Комната\'",
            "Комната.КодКомнаты as \'Код комнаты\'",
            "Комната.Класс as \'Класс\'",
            "Комната.КолвоМест as \'Колво мест\'",
            "Комната.Стоимость as \'Стоимость\'",
            "Сотрудник as \'Сотрудник\'",
            "Сотрудник.Имя as \'Имя\'",
            "Сотрудник.Фамилия as \'Фамилия\'",
            "Сотрудник.Отчесвто as \'Отчество\'",
            "Сотрудник.Должность as \'Должность\'",
            "Сотрудник.Должность.Наименование as \'Наименование должности\'"}, Hidden=new string[] {
            "Комната.КодКомнаты",
            "Комната.Класс",
            "Комната.КолвоМест",
            "Комната.Стоимость",
            "Сотрудник.Имя",
            "Сотрудник.Фамилия",
            "Сотрудник.Отчесвто",
            "Сотрудник.Должность.Наименование"})]
    [AssociatedDetailViewAttribute("ДоступE", "РегистрЗаписи", "РегистрЗаписиE", true, "", "Регистр записи", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("ДоступE", "Гости", "ГостиE", true, "", "Гости", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ДоступE", "Комната", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Класс")]
    [MasterViewDefineAttribute("ДоступE", "Сотрудник", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Имя")]
    [View("ДоступL", new string[] {
            "КодДоступа as \'Код доступа\'",
            "Доступ as \'Доступ\'",
            "Комната.КодКомнаты as \'Код комнаты\'",
            "Комната.КолвоМест as \'колво мест\'",
            "Комната.Стоимость as \'стоимость\'",
            "Комната.Класс as \'Класс\'",
            "Сотрудник.Имя as \'Имя\'",
            "Сотрудник.Фамилия as \'Фамилия\'",
            "Сотрудник.Отчесвто as \'Отчество\'",
            "Сотрудник.Должность.Наименование as \'Наименование должности\'"})]
    public class Доступ : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодДоступа;
        
        private string fДоступ;
        
        private IIS.OtelKursach2.Комната fКомната;
        
        private IIS.OtelKursach2.Сотрудник fСотрудник;
        
        private IIS.OtelKursach2.DetailArrayOfГости fГости;
        
        private IIS.OtelKursach2.DetailArrayOfРегистрЗаписи fРегистрЗаписи;
        
        // *** Start programmer edit section *** (Доступ CustomMembers)

        // *** End programmer edit section *** (Доступ CustomMembers)

        
        /// <summary>
        /// Доступ.
        /// </summary>
        // *** Start programmer edit section *** (Доступ.Доступ CustomAttributes)

        // *** End programmer edit section *** (Доступ.Доступ CustomAttributes)
        [StrLen(255)]
        public virtual string Доступ
        {
            get
            {
                // *** Start programmer edit section *** (Доступ.Доступ Get start)

                // *** End programmer edit section *** (Доступ.Доступ Get start)
                string result = this.fДоступ;
                // *** Start programmer edit section *** (Доступ.Доступ Get end)

                // *** End programmer edit section *** (Доступ.Доступ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Доступ.Доступ Set start)

                // *** End programmer edit section *** (Доступ.Доступ Set start)
                this.fДоступ = value;
                // *** Start programmer edit section *** (Доступ.Доступ Set end)

                // *** End programmer edit section *** (Доступ.Доступ Set end)
            }
        }
        
        /// <summary>
        /// КодДоступа.
        /// </summary>
        // *** Start programmer edit section *** (Доступ.КодДоступа CustomAttributes)

        // *** End programmer edit section *** (Доступ.КодДоступа CustomAttributes)
        public virtual int КодДоступа
        {
            get
            {
                // *** Start programmer edit section *** (Доступ.КодДоступа Get start)

                // *** End programmer edit section *** (Доступ.КодДоступа Get start)
                int result = this.fКодДоступа;
                // *** Start programmer edit section *** (Доступ.КодДоступа Get end)

                // *** End programmer edit section *** (Доступ.КодДоступа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Доступ.КодДоступа Set start)

                // *** End programmer edit section *** (Доступ.КодДоступа Set start)
                this.fКодДоступа = value;
                // *** Start programmer edit section *** (Доступ.КодДоступа Set end)

                // *** End programmer edit section *** (Доступ.КодДоступа Set end)
            }
        }
        
        /// <summary>
        /// Доступ.
        /// </summary>
        // *** Start programmer edit section *** (Доступ.Комната CustomAttributes)

        // *** End programmer edit section *** (Доступ.Комната CustomAttributes)
        [PropertyStorage(new string[] {
                "Комната"})]
        [NotNull()]
        public virtual IIS.OtelKursach2.Комната Комната
        {
            get
            {
                // *** Start programmer edit section *** (Доступ.Комната Get start)

                // *** End programmer edit section *** (Доступ.Комната Get start)
                IIS.OtelKursach2.Комната result = this.fКомната;
                // *** Start programmer edit section *** (Доступ.Комната Get end)

                // *** End programmer edit section *** (Доступ.Комната Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Доступ.Комната Set start)

                // *** End programmer edit section *** (Доступ.Комната Set start)
                this.fКомната = value;
                // *** Start programmer edit section *** (Доступ.Комната Set end)

                // *** End programmer edit section *** (Доступ.Комната Set end)
            }
        }
        
        /// <summary>
        /// Доступ.
        /// </summary>
        // *** Start programmer edit section *** (Доступ.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (Доступ.Сотрудник CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудник"})]
        [NotNull()]
        public virtual IIS.OtelKursach2.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (Доступ.Сотрудник Get start)

                // *** End programmer edit section *** (Доступ.Сотрудник Get start)
                IIS.OtelKursach2.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (Доступ.Сотрудник Get end)

                // *** End programmer edit section *** (Доступ.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Доступ.Сотрудник Set start)

                // *** End programmer edit section *** (Доступ.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (Доступ.Сотрудник Set end)

                // *** End programmer edit section *** (Доступ.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// Доступ.
        /// </summary>
        // *** Start programmer edit section *** (Доступ.Гости CustomAttributes)

        // *** End programmer edit section *** (Доступ.Гости CustomAttributes)
        public virtual IIS.OtelKursach2.DetailArrayOfГости Гости
        {
            get
            {
                // *** Start programmer edit section *** (Доступ.Гости Get start)

                // *** End programmer edit section *** (Доступ.Гости Get start)
                if ((this.fГости == null))
                {
                    this.fГости = new IIS.OtelKursach2.DetailArrayOfГости(this);
                }
                IIS.OtelKursach2.DetailArrayOfГости result = this.fГости;
                // *** Start programmer edit section *** (Доступ.Гости Get end)

                // *** End programmer edit section *** (Доступ.Гости Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Доступ.Гости Set start)

                // *** End programmer edit section *** (Доступ.Гости Set start)
                this.fГости = value;
                // *** Start programmer edit section *** (Доступ.Гости Set end)

                // *** End programmer edit section *** (Доступ.Гости Set end)
            }
        }
        
        /// <summary>
        /// Доступ.
        /// </summary>
        // *** Start programmer edit section *** (Доступ.РегистрЗаписи CustomAttributes)

        // *** End programmer edit section *** (Доступ.РегистрЗаписи CustomAttributes)
        public virtual IIS.OtelKursach2.DetailArrayOfРегистрЗаписи РегистрЗаписи
        {
            get
            {
                // *** Start programmer edit section *** (Доступ.РегистрЗаписи Get start)

                // *** End programmer edit section *** (Доступ.РегистрЗаписи Get start)
                if ((this.fРегистрЗаписи == null))
                {
                    this.fРегистрЗаписи = new IIS.OtelKursach2.DetailArrayOfРегистрЗаписи(this);
                }
                IIS.OtelKursach2.DetailArrayOfРегистрЗаписи result = this.fРегистрЗаписи;
                // *** Start programmer edit section *** (Доступ.РегистрЗаписи Get end)

                // *** End programmer edit section *** (Доступ.РегистрЗаписи Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Доступ.РегистрЗаписи Set start)

                // *** End programmer edit section *** (Доступ.РегистрЗаписи Set start)
                this.fРегистрЗаписи = value;
                // *** Start programmer edit section *** (Доступ.РегистрЗаписи Set end)

                // *** End programmer edit section *** (Доступ.РегистрЗаписи Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДоступE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДоступE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДоступE", typeof(IIS.OtelKursach2.Доступ));
                }
            }
            
            /// <summary>
            /// "ДоступL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДоступL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДоступL", typeof(IIS.OtelKursach2.Доступ));
                }
            }
        }
    }
}
